### ISSUE TITLE
Using linkColor change the links color to the default WebView blue <a> color

### ISSUE THREAD

**Issue by axiel7** [NuPlay/RichText#19]
If I don't set the `.linkColor`, the link color uses the RichText default light blue color. But when I try to set my custom color, it does not change to the desired color and fallbacks to the dark blue link color.

```swift
RichText(html: htmlString)
        .linkColor(light: Color.white, dark: Color.white)
```
I am not sure if is related but I am testing this on the latest Xcode 14 beta 5.

**Comment by NuPlay** [comment]
Thanks for letting me know I fixed it in version 2.0.1
