### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by unequalsine** [NuPlay/RichText#34]
seems like a very capable library, but can unfortunately not be used for a macOS SwiftUI application due to the lack of UIKit availability.

**Comment by NuPlay** [comment]
To make this library also available for macOS, I'll try to develop it using AppKit on macOS.

This will take some time, but I'll do my best. And I target to make it within two weeks.

**Comment by NuPlay** [comment]
Added support for macOS via #36.
You can use v2.3.0 or higher.

I appreciate your valuable feedback. If you have any further concerns or issues, feel free to let me know.
