### ISSUE TITLE
Feature: Additional type to LinkOpenType

### ISSUE THREAD

**Issue by vidalhara** [NuPlay/RichText#41]
Need:  
 - Handle clicked url without opening Safari

Possible Solution: 
 - Can be added a new type as custom and a parameter as closure which gets URL in order to execute when url selected.

**Comment by NuPlay** [comment]
Thank you for raising the issue and also for submitting the PR  that adds the feature.
I have released version [2.3.1](https://github.com/NuPlay/RichText/releases/tag/2.3.1),  which includes this new functionality.
