### ISSUE TITLE
LinkOpenType - custom type

### ISSUE THREAD

**Issue by mauryalamin** [NuPlay/RichText#46]
Could be my inexperience, but I was hoping to use this new feature in the following way: 

1. I receive HTML content via an api
2. The HTML contains links that I would like to open within my app, using it to display the content in my UI (not in any browser)
3. Some of the links from this api come in weird formats like "<a href=\"/gary-busey/4005-1780/\" data-ref-id=\"4005-1780\">Gary Busey</a>"
4. I was planning to process the link using Regex to rewrite it and load the content in a new view in my app
5. I tried some simple test code like: 
```
.linkOpenType(.custom({ url in
      print(url)
 }))
```
but I'm getting the following messages in the Output window after clinking the link:
```
0x16e1300c0 - [PID=77634] WebProcessProxy::checkURLReceivedFromWebProcess: Received an unexpected URL from the web process
0x1060a9018 - [pageProxyID=14, webPageID=15, PID=77634] WebPageProxy::Ignoring request to load this main resource because it is outside the sandbox
```

If I click a traditional-looking link like:
<a href=\"https://api.site.com/gary-busey/4005-15789/\" data-ref-id=\"4005-15789\">Gary Busey</a>
My code will print the URL as expected.

Am I totally off base, trying to use the new feature in this way? If so, what's the intended use of this feature?

Thanks
Maury

**Comment by NuPlay** [comment]
I've made the change you want in the [`feature/#46-change-customtype`](https://github.com/NuPlay/RichText/tree/feature/%2346-change-customtype)
If you choose linkOpenType as custom, it will always return a link.

Give it a try, and let me know if it works the way you want.

**Comment by mauryalamin** [comment]
I tested the change and it is working as expected.

Thanks!!!
