### ISSUE TITLE
Normal text doesn't show up

### ISSUE THREAD

**Issue by afern247** [NuPlay/RichText#8]
Hi, I have the following text:

`USDC is a fully collateralized US dollar stablecoin. USDC is the bridge between dollars and trading on cryptocurrency exchanges. The technology behind CENTRE makes it possible to exchange value between people, businesses and financial institutions just like email between mail services and texts between SMS providers. We believe by removing artificial economic borders, we can create a more inclusive global economy. `

and it's not showing up:

![image](https://user-images.githubusercontent.com/34192856/150710646-31dc897f-32e0-40c8-85cb-1fb89b68bd38.png)

**Comment by NuPlay** [comment]
This library is designed to display only those wrapped in Html tags.
	
I'm thinking about how to deal with it.
If there is no tag like that, what kind of tag should it be given,
And if a tag is included but only a specific part doesn't have a tag?

There are various situations like this, so I'll think about it a little more.

**Comment by afern247** [comment]
> This library is designed to display only those wrapped in Html tags.
> 
> I'm thinking about how to deal with it. If there is no tag like that, what kind of tag should it be given, And if a tag is included but only a specific part doesn't have a tag?
> 
> There are various situations like this, so I'll think about it a little more.

Sure thing. For example I have a text which is like the above, and in some part of the text there might be some links, other texts might just be plain like that.
